postgres:
        build: ./Postgres
        hostname: postgres
        expose:
                - 5432
                - 80
        ports:
                - "80:80"
                - "5432:5432"

receiver:
        build: ./receiver
        hostname: receiver
        expose:
                - 8181
                - 61616
        ports:
                - "10003:8181"
                - "61616:61616"
        links:
                - postgres
        environment:
                - SmartGatewayActiveMQBroker="192.168.42.1:4711"


rules:
        build: ./Rules
        hostname: iotdatacenterrules
        links:
               - receiver
               - bpm
               - jdg
        environment:
               - mqttBrokerURL=192.168.178.103


bpm:
        build:  ./bpm
        hostname: bpm
        expose:
               - 8080
        ports:
               - 8080:8080
        links:
               - receiver
               - jdg

jdg:
        build:  ./DataGrid
        hostname: jdg
        expose:
               - 8080
               - 11222
        ports:
               - 11222:11222
