postgres:
        build: ./Postgres
        hostname: postgres
        expose:
                - 5432
                - 80
        ports:
                - "80:80"
                - "5432:5432"

receiver:
        build: ./receiver
        hostname: receiver
        expose:
                - 8181
                - 61616
        ports:
                - "8181:8181"
                - "61616:61616"
        links:
                - postgres
        environment:
                - GATEWAY_JMS_BROKER_URL=tcp://192.168.42.1:61616
                - BROKER_ADMIN_UID=admin
                - BROKER_ADMIN_PASSWD=change12_me
        volumes:
               - ~/.m2/repository:/home/psteiner/.m2/repository


rules:
        build: ./Rules
        hostname: rules
        links:
               - receiver
               - bpm
               - jdg
        environment:
                - SOURCE_AMQ_BROKER=tcp://receiver:61616
                - TARGET_MQTT_BROKER=tcp://192.168.42.1:1883
                - SOURCE_QUEUE=message.to.rules
                - TARGET_QUEUE=message.to.datacenter
                - BROKER_ADMIN_UID=admin
                - BROKER_ADMIN_PASSWD=change12_me
        volumes:
                - ./Rules/target:/home/psteiner/target
                - ~/.m2/repository:/home/psteiner/.m2/repository

bpm:
        build:  ./bpm
        hostname: bpm
        expose:
               - 8080
        ports:
               - 8080:8080
        links:
               - receiver
               - jdg
        volumes:
               - ~/.m2/repository:/home/psteiner/.m2/repository

jdg:
        build:  ./DataGrid
        hostname: jdg
        expose:
               - 8080
               - 11222
        ports:
               - 11222:11222
        volumes:
               - ~/.m2/repository:/home/psteiner/.m2/repository
