postgres:
        build: ./Postgres
        hostname: postgres
        expose:
                - 5432
                - 80
        ports:
                - "80:80"
                - "5432:5432"

receiver:
        build: ./receiver
        hostname: receiver
        expose:
                - 8181
                - 61616
        ports:
                - "8181:8181"
                - "61616:61616"
        links:
                - postgres
        environment:
                # URL of Broker on Gateway
                - GATEWAY_JMS_BROKER_URL=tcp://192.168.42.1:61616
                # - GATEWAY_JMS_BROKER_URL=tcp://192.168.178.116:61616
                - BROKER_ADMIN_UID=admin
                - BROKER_ADMIN_PASSWD=change12_me
        privileged: true
        volumes:
                - ./receiver/target:/home/psteiner/target
                - ~/.m2/repository:/home/psteiner/.m2/repository


rules:
        build: ./Rules
        hostname: rules
        links:
               - receiver
               - bpm
               - jdg
        environment:
                # URL of Broker for Datacenter. Usually no need to change this
                - SOURCE_AMQ_BROKER=tcp://receiver:61616
                # URL of Broker on Gateway
                - TARGET_MQTT_BROKER=tcp://192.168.42.1:1883
                # - TARGET_MQTT_BROKER=tcp://192.168.178.116:1883
                - SOURCE_QUEUE=message.to.rules
                - TARGET_QUEUE=message.to.datacenter
                - BROKER_ADMIN_UID=admin
                - BROKER_ADMIN_PASSWD=change12_me
        privileged: true
        volumes:
                - ./Rules/target:/home/psteiner/target
                - ~/.m2/repository:/home/psteiner/.m2/repository

bpm:
        build:  ./bpm
        hostname: bpm
        expose:
               - 8080
        ports:
               - 8080:8080
        links:
               - receiver
               - jdg
               - nexus3
        privileged: true
        volumes:
               - ~/.m2/repository:/home/psteiner/.m2/repository

jdg:
        build:  ./DataGrid
        hostname: jdg
        expose:
               - 8080
               - 11222
        ports:
               - 11222:11222
        privileged: true
        volumes:
               - ~/.m2/repository:/home/psteiner/.m2/repository

zeppelin:
        build: ./Zeppelin
        hostname: zeppelin
        expose:
               - 8080
        ports:
               - 7070:8080
        links:
               - postgres
        privileged: true
        volumes:
               - ~/.m2/repository:/home/psteiner/.m2/repository

nexus3:
       image: sonatype/nexus:latest
       hostname: nexus3
       expose:
               - 8081
       ports:
               - 8081:8081
       privileged: true
