postgres:
        build: ./Postgres
        hostname: postgres
        expose:
                - 5432
                - 80
        ports:
                - "80:80"
                - "5432:5432"

receiver:
        build: ./receiver
        hostname: receiver
        expose:
                - 8181
                - 61616
        ports:
                - "10003:8181"
                - "61616:61616"
        links:
                - postgres

rules:
        build: ./Rules
        hostname: iotdatacenterrules
        links:
               - receiver
